import turtle
window=turtle.Screen()
window.bgcolor("white")

circle=turtle.Turtle()
circle.color("yellow")
circle.begin_fill()
circle.circle(100)
circle.end_fill()


circle=turtle.Turtle()
circle.penup()
circle.goto(-40,100)
circle.pendown()
circle.begin_fill()
circle.color("black")
circle.circle(20)
circle.end_fill()

circle=turtle.Turtle()
circle.penup()
circle.goto(40,100)
circle.pendown()
circle.begin_fill()
circle.color("black")
circle.circle(20)
circle.end_fill()

rectangle=turtle.Turtle()
rectangle.penup()
rectangle.goto(-50,50)
rectangle.pendown()
rectangle.begin_fill()
rectangle.color("black")
rectangle.forward(200)
rectangle.right(40)
rectangle.pendown()
rectangle.end_fill()

input("press enter to finish")
turtle.done()
